### ISSUE TITLE
配置类型错误

### ISSUE THREAD

**Issue by Sevenyine** [Reversedeer/nonebot_plugin_eventmonitor#2]
这里的bot_name的类型是int吗？似乎和例子不太符合，是文档写错了吗（）
![image](https://user-images.githubusercontent.com/65720409/227768601-44eca103-3c82-4984-8f63-4444bc550e7a.png)

**Comment by Reversedeer** [comment]
是的，感谢您的反馈
pypi最新v0.1.2，git稍后更新~~~~

**Comment by Reversedeer** [comment]
github已更新，请关注readme.md
