### ISSUE TITLE
能否在关闭功能后不发送“未启用该功能”的消息

### ISSUE THREAD

**Issue by ABKQPO** [Reversedeer/nonebot_plugin_eventmonitor#20]

**Comment by Reversedeer** [comment]
可以，你需要删除[utils.py#L20](https://github.com/Reversedeer/nonebot_plugin_eventmonitor/blob/ff4cab570b5ffea6fc9710bd8532354f3c5cc126/nonebot_plugin_eventmonitor/utils.py#L20)
