### ISSUE TITLE
如何关闭当超管/bot加入群后自动发送的信息

### ISSUE THREAD

**Issue by ABKQPO** [Reversedeer/nonebot_plugin_eventmonitor#21]

**Comment by Reversedeer** [comment]
请认真阅读readme中关于指令的解释和用法

**Comment by ABKQPO** [comment]
我已阅读readme的指令，但是我并没有找到将其设置为默认关闭或关闭加群时自动发送消息，如何删除bot加群发送消息和检测superadmin发送的特殊欢迎消息？我希望可以将其设置为普通用户欢迎

**Comment by Reversedeer** [comment]
你可以将[admin.py#L50,
L51和L55](https://github.com/Reversedeer/nonebot_plugin_eventmonitor/blob/ff4cab570b5ffea6fc9710bd8532354f3c5cc126/nonebot_plugin_eventmonitor/admin.py#L50)替换为pass(注意缩进)
将[utils.py#L47,L76](https://github.com/Reversedeer/nonebot_plugin_eventmonitor/blob/ff4cab570b5ffea6fc9710bd8532354f3c5cc126/nonebot_plugin_eventmonitor/utils.py#L47)加入"red_package"后加上"add_user"

**Comment by Reversedeer** [comment]
没问题就close了
