### ISSUE TITLE
你好请问一下

### ISSUE THREAD

**Issue by xiner1314522** [Reversedeer/nonebot_plugin_eventmonitor#25]
请问一下安装了这个，群成员变动退群进群没有提示是怎么回事呢谢谢

**Comment by Reversedeer** [comment]
如果您使用Watch协议，群成员变动无法检测到；
如果您使用安卓协议，请确认插件是否正常工作。（如有报错，请帖错误日志）
此外，本插件缺少维护，可能不支持最新版nonebot（高考结束就更QWQ）

**Comment by a114511a** [comment]
请问一下，装了这个插件戳一戳并没有生效是怎么回事呢？
ntqq+nonebot2
