### ISSUE TITLE
戳一戳用不了

### ISSUE THREAD

**Issue by a114511a** [Reversedeer/nonebot_plugin_eventmonitor#26]
请问一下，装了这个插件戳一戳并没有生效是怎么回事呢？
ntqq+nonebot2

**Comment by Reversedeer** [comment]
有报错吗贴出来看看

**Comment by Reversedeer** [comment]
ntqq+nb2没有测试过，我目前在使用的是gocq+nb2，如果有报错贴出来看看

**Comment by a114511a** [comment]
![image](https://github.com/Reversedeer/nonebot_plugin_eventmonitor/assets/152017388/140e8485-0307-4f32-9375-290b4c6a5486)
没有报错，单纯没有任何反应

**Comment by Reversedeer** [comment]
我这边没办法复现你的问题，只能暂时搁置，或者等维护后看看能不能解决

**Comment by Reversedeer** [comment]
你好ntqq无法使用戳一戳，不是本插件的问题
如果你使用llonebot详情见https://llonebot.github.io/zh-CN/develop/event
