### ISSUE TITLE
似乎SUPERUSERS配置的类型也是错的

### ISSUE THREAD

**Issue by Sevenyine** [Reversedeer/nonebot_plugin_eventmonitor#3]
SUPERUSERS=[“”]这样配置之后bot仍然说未配置，文档里的类型给的是int，是不是又错了😂
![7B3E558C-30EA-471A-80C0-75C953B03E7E](https://user-images.githubusercontent.com/65720409/227866548-ed45913f-10d4-459c-843a-974b9d7ed809.jpeg)
![7FC46A65-D914-4FB8-B1AB-F137EBD143E3](https://user-images.githubusercontent.com/65720409/227866579-7cf263d0-72af-4abb-9df6-315a63267d3d.jpeg)

**Comment by Sevenyine** [comment]
> 在honour.py的第10行结尾：SUPERUSERS应该改为小写superusers，这次更新把这个文件回滚了emmm
> 你也可以直接手动更新，或等待发版v0.1.3

这个我能改（笑）开PR啦 #4

**Comment by Reversedeer** [comment]
点点star
