### ISSUE TITLE
一个建议（？

### ISSUE THREAD

**Issue by SEVEN-6174** [Reversedeer/nonebot_plugin_eventmonitor#6]
虽然但是,bot本身的qq可以用event.self_id获取
然后这样就可以通过api来获取qq对应的用户名了
所以bot的qq号和bot名称其实没必要
不改...麻烦一点而已
(然后顺便看看能不能改了)

**Comment by Reversedeer** [comment]
可以，我也想到了，总是忘记改，下次版本将会更新

**Comment by Reversedeer** [comment]
已发版v0.1.5
