### ISSUE TITLE
希望新增可配置部分功能开关的功能

### ISSUE THREAD

**Issue by glamorgan9826** [Reversedeer/nonebot_plugin_eventmonitor#9]
比如并不需要红包运气王以及群文件上传的通知，希望可以配置不同事件监控的开启或关闭
想了两种思路：
1、仅在配置文件里加载插件时初始化的一次性配置，所有群通用，无法热修改，无分群管理，对代码改动较小
2、新增指令进行热修改不同群的功能状态，以适应不同类型群组的需求，需要本地存储不同群组的配置文件

个人感觉这个功能还是比较实用的，希望能做出来，尤其是日后添加的监控事件越来越多，并不是每个群都需要用到全部的事件监控，可以早一些把这个控制功能实现。
（其实是我平时真的不是很用的到红包运气王之类的功能，所以哪怕是第一种实现也挺有用）

**Comment by Reversedeer** [comment]
还有个问题，运气王监测有效果吗

**Comment by Nenot233** [comment]
运气王正常

**Comment by Reversedeer** [comment]
更新了，抱歉一直在拖
